---
title: "Project 1"
author: "Rachel Robinson"
date: "2026-03-31"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Loading and preprocessing the data

```{r, echo=TRUE}
activity <- read.csv("~/fileshare/activity.csv")
activity$date <- as.Date(activity$date)
head(activity)
summary(activity)
```

## What is mean total number of steps taken per day?

```{r, echo=TRUE}
daily_steps <- aggregate(steps ~ date, data = activity, sum, na.rm = TRUE)
head(daily_steps)
```

```{r, echo=TRUE}
hist(daily_steps$steps,
     main = "Total Steps Taken Per Day",
     xlab = "Total Daily Steps",
     col = "yellow",
     border = "white")
```

```{r, echo=TRUE}
mean_steps <- mean(daily_steps$steps)
median_steps <- median(daily_steps$steps)

mean_steps
median_steps
```


## What is the average daily activity pattern?

```{r, echo=TRUE}
interval_avg <- aggregate(steps ~ interval, data = activity, mean, na.rm = TRUE)
head(interval_avg)
```

```{r, echo=TRUE}
plot(interval_avg$interval,
     interval_avg$steps,
     type = "l",
     xlab = "5-minute Interval",
     ylab = "Average Number of Steps",
     main = "Average Daily Activity Pattern")
```

```{r, echo=TRUE}
max_interval <- interval_avg[which.max(interval_avg$steps), ]
max_interval
```


## Imputing missing values

```{r, echo=TRUE}
total_missing <- sum(is.na(activity$steps))
total_missing
```


```{r, echo=TRUE}
activity_filled <- activity

for(i in 1:nrow(activity_filled)) {
  if(is.na(activity_filled$steps[i])) {
    this_interval <- activity_filled$interval[i]
    interval_mean <- interval_avg$steps[interval_avg$interval == this_interval]
    activity_filled$steps[i] <- interval_mean
  }
}

sum(is.na(activity_filled$steps))
```

```{r, echo=TRUE}
daily_steps_filled <- aggregate(steps ~ date, data = activity_filled, sum)
head(daily_steps_filled)
```

```{r, echo=TRUE}
hist(daily_steps_filled$steps,
     main = "Total Steps Taken Per Day After Imputing Missing Values",
     xlab = "Total Daily Steps",
     col = "lightgreen",
     border = "white")
```

```{r, echo=TRUE}
mean_steps_filled <- mean(daily_steps_filled$steps)
median_steps_filled <- median(daily_steps_filled$steps)

mean_steps_filled
median_steps_filled
```


## Are there differences in activity patterns between weekdays and weekends?

```{r, echo=TRUE}
activity_filled$day_type <- ifelse(weekdays(activity_filled$date) %in% c("Saturday", "Sunday"),
                                   "weekend",
                                   "weekday")

activity_filled$day_type <- as.factor(activity_filled$day_type)

head(activity_filled)
```

```{r, echo=TRUE}
interval_daytype <- aggregate(steps ~ interval + day_type,
                              data = activity_filled,
                              mean)
head(interval_daytype)
```

```{r, echo=TRUE}
library(lattice)

xyplot(steps ~ interval | day_type,
       data = interval_daytype,
       type = "l",
       layout = c(1, 2),
       xlab = "5-minute Interval",
       ylab = "Average Number of Steps",
       main = "Average Daily Activity Pattern: Weekday vs Weekend")
```

